from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime


def create_pdf(notes, filename="study_notes.pdf"):

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    content = []

    # Title
    content.append(
        Paragraph(
            "⚡ MindForge AI Study Notes",
            styles["Title"]
        )
    )

    content.append(Spacer(1, 12))

    # Date
    content.append(
        Paragraph(
            f"Generated on: {datetime.now().strftime('%d %B %Y')}",
            styles["Italic"]
        )
    )

    content.append(Spacer(1, 20))

    # Heading
    content.append(
        Paragraph(
            "Generated Learning Material",
            styles["Heading2"]
        )
    )

    content.append(Spacer(1, 10))

    # Notes Content
    content.append(
        Paragraph(
            notes.replace("\n", "<br/>"),
            styles["BodyText"]
        )
    )

    content.append(Spacer(1, 20))

    # Footer
    content.append(
        Paragraph(
            "Generated by MindForge AI",
            styles["Italic"]
        )
    )

    doc.build(content)

    return filename